# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.36
#
# Don't modify this file, modify the SWIG interface instead.
# This file is compatible with both classic and new-style classes.

import _radint_ng
import new
new_instancemethod = new.instancemethod
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'PySwigObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError,name

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

import types
try:
    _object = types.ObjectType
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0
del types


class radintArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, radintArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, radintArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _radint_ng.new_radintArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _radint_ng.delete_radintArray
    __del__ = lambda self : None;
    def __getitem__(*args): return _radint_ng.radintArray___getitem__(*args)
    def __setitem__(*args): return _radint_ng.radintArray___setitem__(*args)
    def cast(*args): return _radint_ng.radintArray_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _radint_ng.radintArray_frompointer
    if _newclass:frompointer = staticmethod(_radint_ng.radintArray_frompointer)
radintArray_swigregister = _radint_ng.radintArray_swigregister
radintArray_swigregister(radintArray)
radintArray_frompointer = _radint_ng.radintArray_frompointer

class radintmaskArray(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, radintmaskArray, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, radintmaskArray, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _radint_ng.new_radintmaskArray(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _radint_ng.delete_radintmaskArray
    __del__ = lambda self : None;
    def __getitem__(*args): return _radint_ng.radintmaskArray___getitem__(*args)
    def __setitem__(*args): return _radint_ng.radintmaskArray___setitem__(*args)
    def cast(*args): return _radint_ng.radintmaskArray_cast(*args)
    __swig_getmethods__["frompointer"] = lambda x: _radint_ng.radintmaskArray_frompointer
    if _newclass:frompointer = staticmethod(_radint_ng.radintmaskArray_frompointer)
radintmaskArray_swigregister = _radint_ng.radintmaskArray_swigregister
radintmaskArray_swigregister(radintmaskArray)
radintmaskArray_frompointer = _radint_ng.radintmaskArray_frompointer

doradint = _radint_ng.doradint


